<a href="https://colab.research.google.com/github/JuminaCahyani40/11181040_JuminaCahyani_DM_IF-ITK/blob/master/DATA_MINING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [83]:
#pip install sklearn

In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [86]:
iris_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IRIS.csv")
iris_data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [87]:
iris_data.shape

(150, 5)

In [88]:
#iris_data.info()

In [89]:
#iris_data.describe()

In [90]:
iris_data['species'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: species, dtype: int64

split data

In [91]:
X=iris_data.drop(['species'], axis=1)
Y=iris_data['species']

In [92]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [93]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=1)

Model Support Vector Machine (Linear)

In [99]:
from sklearn.svm import SVC, LinearSVC

In [100]:
linear_svc = LinearSVC(max_iter=4000)

In [102]:
linear_svc.fit(X_train, Y_train)
yprediksi = linear_svc.predict(X_test)

In [103]:
accuracy_svc=round(accuracy_score(Y_test, yprediksi)* 100, 2)
acc_linear_svc = round(linear_svc.score(X_train, Y_train) * 100, 2)

cm = confusion_matrix(Y_test, yprediksi)
accuracy = accuracy_score(Y_test,yprediksi)
precision =precision_score(Y_test, yprediksi, average='micro')
recall =  recall_score(Y_test, yprediksi,average='micro')
f1 = f1_score(Y_test,yprediksi,average='micro')
print('Confusion matrix for SVC\n',cm)
print('accuracy_SVC: %.3f' %accuracy)
print('precision_SVC: %.3f' %precision)
print('recall_SVC: %.3f' %recall)
print('f1-score_SVC : %.3f' %f1)

Confusion matrix for SVC
 [[11  0  0]
 [ 0 10  3]
 [ 0  0  6]]
accuracy_SVC: 0.900
precision_SVC: 0.900
recall_SVC: 0.900
f1-score_SVC : 0.900


Models Gaussian Naive Bayes

In [94]:
gaussian = GaussianNB()

In [95]:
gaussian.fit(X_train, Y_train)
y_prediksi = gaussian.predict(X_test)

In [96]:
akurasi_nb = round(accuracy_score(Y_test, y_prediksi)*100, 2)
akurasi_gaussian = round(gaussian.score(X_train, Y_train)*100, 2)

In [97]:
cm = confusion_matrix(Y_test, y_prediksi)
acc_pred = accuracy_score(Y_test, y_prediksi)
precision = precision_score(Y_test, y_prediksi, average="micro")
recall =  recall_score(Y_test, y_prediksi,average='micro')
f1 = f1_score(Y_test,y_prediksi,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %acc_pred)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
accuracy_Naive Bayes: 0.967
precision_Naive Bayes: 0.967
recall_Naive Bayes: 0.967
f1-score_Naive Bayes : 0.967
